### ISSUE TITLE
Mention UTM workaround?

### ISSUE THREAD

**Issue by ink-splatters** [lixiljp/qemu_docker_on_mac_m1#1]
Hi,

thanks a lot for the great repo.

Seems there is quite straightforward workaround for UTM’s networking issue:

https://mac.getutm.app/gallery/ubuntu-20-04#networking-is-unavailable-after-switching-between-console-only-and-full-graphics-modes

Would you mind mentioning it in your comparison? 

Cheers,
Peter

**Comment by duc2019** [comment]
Hi, thank you for notice, I added your link to readme.
